### ISSUE TITLE
Seeker is not working

### ISSUE THREAD

**Issue by edwinharly** [codealchemist/youtube-audio-server#10] opened 2018-08-12 07:19 UTC

**Comment by codealchemist** [comment] 2018-10-23 17:52
Able to reproduce on Chrome 70.0.3538.67.
Works OK on Firefox 61.0.2.
All on OSX.

Will investigate what's going on on Chrome.
Thanks for reporting.

**Comment by codealchemist** [comment] 2018-10-24 22:35
Seeking doesn't work on Chrome because we're just piping the mp3 stream into the express response.
Chrome needs a partial response with byte ranges to properly do seeking.
Wondering why this is not the case for Firefox...

I've found an express middleware that implements partial responses:
https://www.npmjs.com/package/send-seekable

But... I wasn't able to find a performant solution to properly implement it since we need to know the total amount of bytes that will be transferred before sending the response.

I've played converting the stream to a buffer but it is too costly and takes too long to respond.
I accept suggestion to properly do this in a performant way.

Thx!

**Comment by codealchemist** [comment] 2018-11-26 16:34
The new endpoint `/chunk/[videoId]` allows chunked responses that will allow seeking to work on Google Chrome.

See #17. Thx!

**Closed as completed by codealchemist** 2018-11-26 16:34 UTC
Labels: help wanted
